# Generated by Django 6.0.1 on 2026-01-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='fa-building', max_length=50)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('hire_limit', models.IntegerField(default=30, help_text='Days within which to register new hires')),
                ('resign_limit', models.IntegerField(default=15, help_text='Days within which to process resignations')),
                ('sync_ssf', models.BooleanField(default=True, help_text='Enable SSF sync for this worksite')),
                ('sync_aia', models.BooleanField(default=True, help_text='Enable AIA sync for this worksite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
