# Generated by Django 6.0.1 on 2026-03-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksite',
            name='hire_limit',
        ),
        migrations.RemoveField(
            model_name='worksite',
            name='resign_limit',
        ),
        migrations.AddField(
            model_name='worksite',
            name='aia_custom_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksite',
            name='aia_registration_schedule',
            field=models.CharField(choices=[('1st', 'Next Month 1st'), ('16th', 'Next Month 16th'), ('custom', 'Custom Date')], default='1st', max_length=10),
        ),
        migrations.AddField(
            model_name='worksite',
            name='aia_resign_limit',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='worksite',
            name='ssf_custom_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksite',
            name='ssf_registration_schedule',
            field=models.CharField(choices=[('1st', 'Next Month 1st'), ('16th', 'Next Month 16th'), ('custom', 'Custom Date')], default='1st', max_length=10),
        ),
        migrations.AddField(
            model_name='worksite',
            name='ssf_resign_limit',
            field=models.IntegerField(default=15),
        ),
    ]
