# Generated by Django 6.0.1 on 2026-03-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0002_remove_worksite_hire_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksite',
            name='aia_registration_schedule',
            field=models.CharField(choices=[('1st', 'Next Month 1st'), ('16th', 'Next Month 16th'), ('custom', 'Custom Date'), ('today', 'Today')], default='1st', max_length=10),
        ),
        migrations.AlterField(
            model_name='worksite',
            name='ssf_registration_schedule',
            field=models.CharField(choices=[('1st', 'Next Month 1st'), ('16th', 'Next Month 16th'), ('custom', 'Custom Date'), ('today', 'Today')], default='1st', max_length=10),
        ),
    ]
