# Generated by Django 6.0.1 on 2026-03-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0003_alter_worksite_aia_registration_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksite',
            name='aia_resign_limit',
        ),
        migrations.RemoveField(
            model_name='worksite',
            name='ssf_resign_limit',
        ),
        migrations.AddField(
            model_name='worksite',
            name='aia_exit_custom_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksite',
            name='aia_exit_schedule',
            field=models.CharField(choices=[('1st', 'Next Month 1st'), ('16th', 'Next Month 16th'), ('custom', 'Custom Date'), ('today', 'Today')], default='1st', max_length=10),
        ),
        migrations.AddField(
            model_name='worksite',
            name='ssf_exit_custom_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksite',
            name='ssf_exit_schedule',
            field=models.CharField(choices=[('1st', 'Next Month 1st'), ('16th', 'Next Month 16th'), ('custom', 'Custom Date'), ('today', 'Today')], default='1st', max_length=10),
        ),
    ]
