# Generated by Django 6.0.1 on 2026-01-08 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worksites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(help_text='13-digit Thai ID in X-XXXX-XXXXX-XX-X format', max_length=17, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('nationality', models.CharField(default='Thai', max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('employment_date', models.DateField()),
                ('plan', models.CharField(blank=True, help_text='Insurance plan level', max_length=50)),
                ('employee_no', models.CharField(blank=True, help_text='Company employee number', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('benefit_type', models.CharField(choices=[('SSF', 'Social Security Fund'), ('AIA', 'AIA Group Insurance')], default='SSF', max_length=10)),
                ('registration_type', models.CharField(choices=[('REGISTER_IN', 'Register In'), ('REGISTER_OUT', 'Register Out')], default='REGISTER_IN', max_length=20)),
                ('status', models.CharField(choices=[('ENTRY', 'Entry'), ('PENDING', 'Pending'), ('REVIEWING', 'Reviewing'), ('REPORTED', 'Reported'), ('VERIFIED', 'Verified')], default='ENTRY', max_length=20)),
                ('effective_date', models.DateField(blank=True, help_text='Date when benefit becomes effective', null=True)),
                ('resign_reason', models.TextField(blank=True, help_text='Reason for resignation (if REGISTER_OUT)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='worksites.worksite')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_card'], name='employees_e_id_card_3ae5e0_idx'), models.Index(fields=['worksite', 'benefit_type'], name='employees_e_worksit_d37691_idx'), models.Index(fields=['status'], name='employees_e_status_61c2f6_idx')],
            },
        ),
    ]
