# Generated by Django 6.0.1 on 2026-01-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hospital_choice_1',
            field=models.CharField(blank=True, help_text='Primary hospital choice for SSF', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hospital_choice_2',
            field=models.CharField(blank=True, help_text='Secondary hospital choice for SSF', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hospital_choice_3',
            field=models.CharField(blank=True, help_text='Tertiary hospital choice for SSF', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced'), ('separated', 'Separated'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='wage_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
