# Generated by Django 6.0.1 on 2026-01-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_hospital_choice_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, help_text='Job title/position (AIA)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport',
            field=models.CharField(blank=True, help_text='Passport number for non-Thai nationals', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='prefix',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.'), ('prof', 'Prof.')], help_text='Title prefix for AIA enrollment', max_length=10, null=True),
        ),
    ]
