# Generated by Django 6.0.1 on 2026-01-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_designation_employee_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='prefix',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.')], help_text='Title prefix for AIA enrollment', max_length=10, null=True),
        ),
    ]
