# Generated by Django 6.0.1 on 2026-01-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_aia',
            field=models.BooleanField(default=False, help_text='Enrolled in AIA Group'),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_ssf',
            field=models.BooleanField(default=False, help_text='Enroled in Social Security'),
        ),
    ]
