# Generated by Django 6.0.1 on 2026-01-28 08:29

from django.db import migrations

def copy_benefit_type_to_boolean_fields(apps, schema_editor):
    """
    Copy data from benefit_type field to has_ssf and has_aia fields
    """
    Employee = apps.get_model('employees', 'Employee')
    
    # Update all employees with SSF benefit type
    Employee.objects.filter(benefit_type='SSF').update(has_ssf=True, has_aia=False)
    
    # Update all employees with AIA benefit type
    Employee.objects.filter(benefit_type='AIA').update(has_ssf=False, has_aia=True)
    
    print(f"✅ Migrated {Employee.objects.count()} employees")

def reverse_copy(apps, schema_editor):
    """
    Reverse migration - copy data back from boolean fields to benefit_type
    """
    Employee = apps.get_model('employees', 'Employee')
    
    # If they have SSF, set benefit_type to SSF
    Employee.objects.filter(has_ssf=True).update(benefit_type='SSF')
    
    # If they have AIA (and not SSF), set benefit_type to AIA
    Employee.objects.filter(has_aia=True, has_ssf=False).update(benefit_type='AIA')

class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_has_aia_employee_has_ssf'),
    ]

    operations = [
        migrations.RunPython(copy_benefit_type_to_boolean_fields, reverse_copy),
    ]