# Generated by Django 6.0.1 on 2026-01-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_copy_benefit_type_data'),
        ('worksites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_worksit_d37691_idx',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['worksite', 'has_ssf', 'has_aia'], name='employees_e_worksit_7e153b_idx'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='benefit_type',
        ),
    ]
