# Generated by Django 6.0.1 on 2026-02-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_employees_e_worksit_d37691_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aia_status',
            field=models.CharField(blank=True, choices=[('ENTRY', 'Entry'), ('PENDING', 'Pending'), ('REVIEWING', 'Reviewing'), ('REPORTED', 'Reported'), ('VERIFIED', 'Verified')], help_text='AIA registration status (null if not enrolled)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ssf_status',
            field=models.CharField(blank=True, choices=[('ENTRY', 'Entry'), ('PENDING', 'Pending'), ('REVIEWING', 'Reviewing'), ('REPORTED', 'Reported'), ('VERIFIED', 'Verified')], help_text='SSF registration status (null if not enrolled)', max_length=20, null=True),
        ),
    ]
