# Generated by Django 6.0.1 on 2026-02-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_aia_status_employee_ssf_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='processing_out_of',
            field=models.CharField(blank=True, choices=[('SSF', 'Social Security Fund'), ('AIA', 'AIA Group Insurance')], help_text='Tracks which benefit the employee is exiting from (SSF or AIA)', max_length=20, null=True),
        ),
    ]
