# Generated by Django 6.0.1 on 2026-02-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_processing_out_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='processing_out_of',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_exiting_aia',
            field=models.BooleanField(default=False, help_text='True if employee is currently exiting from AIA benefit'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_exiting_ssf',
            field=models.BooleanField(default=False, help_text='True if employee is currently exiting from SSF benefit'),
        ),
    ]
