# Generated by Django 6.0.1 on 2026-02-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_employee_processing_out_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='True if employee exit has been officially confirmed and archived'),
        ),
    ]
