# Generated by Django 6.0.1 on 2026-02-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='employee',
            name='aia_archived',
            field=models.BooleanField(default=False, help_text='True if AIA exit has been officially confirmed and archived'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ssf_archived',
            field=models.BooleanField(default=False, help_text='True if SSF exit has been officially confirmed and archived'),
        ),
    ]
