# Generated by Django 6.0.1 on 2026-02-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_remove_employee_is_archived_employee_aia_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aia_activated',
            field=models.BooleanField(default=False, help_text='True if AIA registration has been officially confirmed and activated'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ssf_activated',
            field=models.BooleanField(default=False, help_text='True if SSF registration has been officially confirmed and activated'),
        ),
    ]
