# Generated by Django 6.0.1 on 2026-02-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_aia_activated_employee_ssf_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aia_status',
            field=models.CharField(blank=True, choices=[('IMPORTED', 'Imported'), ('PENDING', 'Pending'), ('REGISTERED', 'Registered')], help_text='AIA registration status (null if not enrolled)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssf_status',
            field=models.CharField(blank=True, choices=[('IMPORTED', 'Imported'), ('PENDING', 'Pending'), ('REGISTERED', 'Registered')], help_text='SSF registration status (null if not enrolled)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('IMPORTED', 'Imported'), ('PENDING', 'Pending'), ('REGISTERED', 'Registered')], default='IMPORTED', max_length=20),
        ),
    ]
