# Generated by Django 6.0.1 on 2026-02-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_migrate_status_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_book_file',
            field=models.FileField(blank=True, help_text='Bank book cover page', null=True, upload_to='employee_documents/bank_books/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ceb_form_file',
            field=models.FileField(blank=True, help_text='AIA CEB enrollment form', null=True, upload_to='employee_documents/ceb_forms/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id_file',
            field=models.FileField(blank=True, help_text='National ID card scan/photo', null=True, upload_to='employee_documents/national_ids/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='has_ssf',
            field=models.BooleanField(default=False, help_text='Enrolled in Social Security'),
        ),
    ]
