# Generated by Django 6.0.1 on 2026-03-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_employee_bank_book_file_employee_ceb_form_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aia_exit_status',
            field=models.CharField(blank=True, choices=[('IMPORTED', 'Imported'), ('PENDING', 'Pending'), ('REGISTERED', 'Registered')], help_text='AIA exit pipeline status (null if not exiting)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ssf_exit_status',
            field=models.CharField(blank=True, choices=[('IMPORTED', 'Imported'), ('PENDING', 'Pending'), ('REGISTERED', 'Registered')], help_text='SSF exit pipeline status (null if not exiting)', max_length=20, null=True),
        ),
    ]
