# Generated by Django 6.0.1 on 2026-03-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_employee_aia_exit_status_employee_ssf_exit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ssf_type',
            field=models.CharField(blank=True, choices=[('1-03', '1-03 (with hospitals)'), ('1-03/1', '1-03/1 (no hospitals)')], help_text='SSF registration type', max_length=10, null=True),
        ),
    ]
