# Generated by Django 6.0.1 on 2026-04-01 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0018_employee_ssf_type'),
        ('worksites', '0004_remove_worksite_aia_resign_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(choices=[('SSF', 'Social Security Fund'), ('AIA', 'AIA Group Insurance')], max_length=10)),
                ('batch_type', models.CharField(choices=[('REGISTER_IN', 'Entry'), ('REGISTER_OUT', 'Exit')], max_length=20)),
                ('registration_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SUBMITTED', 'Submitted'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employees', models.ManyToManyField(blank=True, related_name='batches', to='employees.employee')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='worksites.worksite')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('worksite', 'benefit', 'batch_type'), name='unique_open_batch_per_worksite_benefit_type')],
            },
        ),
    ]
