# Generated by Django 6.0.1 on 2026-01-08 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_choice_1', models.CharField(blank=True, max_length=200)),
                ('hospital_choice_2', models.CharField(blank=True, max_length=200)),
                ('hospital_choice_3', models.CharField(blank=True, max_length=200)),
                ('processed_by', models.CharField(blank=True, help_text='Admin who processed this', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_queues', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Benefit Queues',
                'ordering': ['-created_at'],
            },
        ),
    ]
