# Generated by Django 6.0.1 on 2026-01-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official hospital name in Thai', max_length=300)),
                ('province', models.CharField(help_text='Province where hospital is located', max_length=100)),
                ('hospital_type', models.CharField(choices=[('PUBLIC', 'Public Hospital'), ('PRIVATE', 'Private Hospital')], help_text='Type of hospital', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Hospitals',
                'ordering': ['province', 'name'],
            },
        ),
    ]
